import = ["/home/picuber/.config/alacritty/colors.toml"]

[env]
# So that the fontsize is actually the fontsize and not scaled
WINIT_X11_SCALE_FACTOR = "1.0"

[font]
size = 8.5

[font.offset]
x = -1
y = 0

[hints]
alphabet = "aoeuidhtns',.pgcrl"

[[hints.enabled]]
command = "firefox"
post_processing = true
regex = "(magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"
