# See /usr/share/doc/alacritty/example/alacritty.yml for details

env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use `alacritty` if it is
  # available, otherwise `xterm-256color` is used.
  #TERM: alacritty
  # So that the fontsize is actually the fontsize and not scaled
  WINIT_X11_SCALE_FACTOR: "1.0"

font:
  normal:
    family: Hack
    style: Regular
  bold:
    family: Hack
    style: Bold
  italic:
    family: Hack
    style: Italic
  bold_italic:
    family: Hack
    style: Bold Italic
  size: 8.5
  offset: {x: -1, y: 0}

colors:
  # Base16 Material Vivid 256 - alacritty color config
  # joshyrobot
  primary:
    background: '0x202124'
    foreground: '0x80868b'
  cursor:
    text: '0x202124'
    cursor: '0x80868b'
  normal:
    black:   '0x202124'
    red:     '0xf44336'
    green:   '0x00e676'
    yellow:  '0xffeb3b'
    blue:    '0x2196f3'
    magenta: '0x673ab7'
    cyan:    '0x00bcd4'
    white:   '0x80868b'
  bright:
    black:   '0x44464d'
    red:     '0xf44336'
    green:   '0x00e676'
    yellow:  '0xffeb3b'
    blue:    '0x2196f3'
    magenta: '0x673ab7'
    cyan:    '0x00bcd4'
    white:   '0xffffff'
  indexed_colors:
    - { index: 16, color: '0xff9800' }
    - { index: 17, color: '0x8d6e63' }
    - { index: 18, color: '0x27292c' }
    - { index: 19, color: '0x323639' }
    - { index: 20, color: '0x676c71' }
    - { index: 21, color: '0x9e9e9e' }

mouse:
  url:
    launcher: firefox
