#!/bin/bash
"${BASH_SOURCE%/*}"/reset
xsetwacom --set "1060PRO Pad pad" Button 10 "key tab"									# canvas only view
xsetwacom --set "1060PRO Pad pad" Button 11 "key +shift +ctrl z -ctrl -shift"			# redo
xsetwacom --set "1060PRO Pad pad" Button 12 "key +ctrl z -ctrl"							# undo
xsetwacom --set "1060PRO Pad pad" Button 13 "key KP_2"									# reset zoom
xsetwacom --set "1060PRO Pad pad" Button 14 "key KP_5"									# reset rotation
xsetwacom --set "1060PRO Pad pad" Button 15 "key shift"
xsetwacom --set "1060PRO Pad pad" Button 16 "key ctrl"
