#!/bin/bash

TEXT="¯\_(ツ)_/¯"
TMPFILE=`mktemp`
 
xclip -o > $TMPFILE
echo $TEXT | xclip -selection clipboard
xdotool key --clearmodifiers Shift+Ctrl+V
cat $TMPFILE | xclip -selection clipboard
rm $TMPFILE
