#!/bin/bash

xsetwacom --set "1060PRO Pen stylus" Button 1 1
xsetwacom --set "1060PRO Pen stylus" Button 2 2
xsetwacom --set "1060PRO Pen stylus" Button 3 3

xsetwacom --set "1060PRO Pad pad" Button 1 1
xsetwacom --set "1060PRO Pad pad" Button 2 2
xsetwacom --set "1060PRO Pad pad" Button 3 3
xsetwacom --set "1060PRO Pad pad" Button 8 8
xsetwacom --set "1060PRO Pad pad" Button 9 9
xsetwacom --set "1060PRO Pad pad" Button 10 10
xsetwacom --set "1060PRO Pad pad" Button 11 11
xsetwacom --set "1060PRO Pad pad" Button 12 12
xsetwacom --set "1060PRO Pad pad" Button 13 13
xsetwacom --set "1060PRO Pad pad" Button 14 14
xsetwacom --set "1060PRO Pad pad" Button 15 15
xsetwacom --set "1060PRO Pad pad" Button 16 16
