require("cfg.plugins.luasnip.all")
require("cfg.plugins.luasnip.tex")
require("cfg.plugins.luasnip.lua")
require("cfg.plugins.luasnip.python")
require("cfg.plugins.luasnip.javascript")
require("cfg.plugins.luasnip.typescript")
require("cfg.plugins.luasnip.typescriptreact")
