#!/bin/bash

case "$1" in
	mic-toggle)
		pactl set-source-mute @DEFAULT_SOURCE@ toggle
		pactl get-source-mute @DEFAULT_SOURCE@ \
            | grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Mic: MUTED" -u low -t 1000
		else
			notify-send "Mic: ON" -u low -t 1000
		fi
		;;
	mic-reset)
		pactl set-source-volume $INPUT 32530
		;;
	sound-toggle)
		pactl set-sink-mute @DEFAULT_SINK@ toggle
		pactl get-sink-mute @DEFAULT_SINK@ toggle \
			| grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Sound: MUTED" -u low -t 1000
		else
			notify-send "Sound: ON" -u low -t 1000
		fi
		;;
	sound-inc)
		pactl set-sink-volume $OUTPUT +1%
		;;
	sound-dec)
		pactl set-sink-volume $OUTPUT -1%
		;;
	*)
		echo "Usage $0 {laptop|dock}-{mic|audio}"
		exit 2

esac

exit 0
