#!/bin/bash

case "$1" in
	mic-toggle)
		pactl set-source-mute alsa_input.pci-0000_06_00.6.analog-stereo toggle
		pactl list sources \
			| grep -A 6 "Name: alsa_input.pci-0000_06_00.6.analog-stereo" \
			| grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Mic: MUTED" -u low -t 1000
		else
			notify-send "Mic: ON" -u low -t 1000
		fi
		;;
	sound-toggle)
		pactl set-sink-mute alsa_output.pci-0000_06_00.6.analog-stereo toggle
		pactl list sinks \
			| grep -A 6 "Name: alsa_output.pci-0000_06_00.6.analog-stereo" \
			| grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Sound: MUTED" -u low -t 1000
		else
			notify-send "Sound: ON" -u low -t 1000
		fi
		;;
	sound-inc)
		pactl set-sink-volume alsa_output.pci-0000_06_00.6.analog-stereo +1%
		;;
	sound-dec)
		pactl set-sink-volume alsa_output.pci-0000_06_00.6.analog-stereo -1%
		;;
	*)
		echo "Usage $0 {laptop|dock}-{mic|audio}"
		exit 2

esac

exit 0
