#!/bin/bash
INTERNAL="eDP"
DP0="DisplayPort-0"
DP1="DisplayPort-1"
HDMI="HDMI-A-0"

case "$1" in 
	normal)
		xrandr --output $INTERNAL --auto --primary --output $HDMI --off --output $DP0 --off --output $DP1 --off
		;;
	docked)
		xrandr --output $INTERNAL --auto --primary --output $HDMI --auto --right-of $INTERNAL
		;;
	extented)
		xrandr --output $INTERNAL --auto --primary --output $HDMI --auto --right-of $INTERNAL
		;;
	presentation)
		xrandr --output $INTERNAL --auto --primary --output $HDMI --auto --same-as $INTERNAL
		;;
    dp0)
        xrandr --output $INTERNAL --auto --primary --output $DP1 --auto --above $INTERNAL
        ;;
    dp1 | work)
        xrandr --output $INTERNAL --auto --primary --output $DP1 --auto --above $INTERNAL
        ;;
	*)
		echo "Usage: $0 {normal|docked|extented|presentation}"
		exit 2
esac

exit 0
