#!/bin/bash

lock() {
	# killall compton
	i3lock-multimonitor -i $HOME/Pictures/Lockscreens/systemLocked_.png
	# compton -b
}

case "$1" in
	lock)
		lock
		;;
	logout)
		i3-msg exit
		;;
	suspend)
		lock && systemctl suspend
		;;
	hibernate)
		lock && systemctl hibernate
		;;
	reboot)
		systemctl reboot
		;;
	shutdown)
		systemctl poweroff
		;;
	*)
		echo "Usage: $0 {lock|blurrLock|logout|suspend|hibernate|reboot|shutdown}"
		exit 2
esac

exit 0


