#!/bin/bash

case "$1" in 
	dock-mic)
		pactl set-source-mute 1 toggle
		pactl list sources | grep Mute | sed '2q;d' | grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Mic(Dock): MUTED" -u low -t 1
		else
			notify-send "Mic(Dock): ON" -u low -t 1
		fi
		;;
	dock-audio)
		pactl set-sink-mute 0 toggle
		pactl list sinks | grep Mute | sed '1q;d' | grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Audio(Dock): MUTED" -u low -t 1
		else
			notify-send "Audio(Dock): ON" -u low -t 1
		fi
		;;
	laptop-mic)
		pactl set-source-mute 3 toggle
		pactl list sources | grep Mute | sed '4q;d' | grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Mic(Laptop): MUTED" -u low -t 1
		else
			notify-send "Mic(Laptop): ON" -u low -t 1
		fi
		;;
	laptop-audio)
		pactl set-sink-mute 1 toggle
		pactl list sinks | grep Mute | sed '2q;d' | grep "Mute: yes" 1>/dev/null
		if [ $? -eq 0 ]; then
			notify-send "Audio(Laptop): MUTED" -u low -t 1
		else
			notify-send "Audio(Laptop): ON" -u low -t 1
		fi
		;;
	*)
		echo "Usage $0 {mic|audio}"
		exit 2
	
esac

exit 0
