#!/bin/bash

case "$1" in
	playpause)
		xdotool search --onlyvisible --class Spotify windowfocus; xdotool key space
		;;
	next)
		xdotool search --onlyvisible --class Spotify windowfocus; xdotool key Control+Right
		;;
	prev)
		xdotool search --onlyvisible --class Spotify windowfocus; xdotool key Control+Left
		;;
	*)
		echo "Usage: $0 {playpause|next|prev}"
		exit 2
esac
